language: objective-c  # [sic]. Travis uses objective-c just to determine it needs to use the xcode cli
osx_image: xcode9.3

# cache:
#   directories:
#     - $HOME/.sonar

branches:
  # Only run push builds for the master branch. PR builds are run nevertheless
  only:
    - master

before_install:
  - echo $TRAVIS_SECURE_ENV_VARS
  - pod repo update > /dev/null
  - ./fastlane/before_install.sh
  - fastlane --version

script:
   - ./fastlane/run.sh  # Decide which lane to run

notifications:
  email: false
